listen = "127.0.0.1:1324"

[upstream]
eth.http = "https://rinkeby-light.eth.linkpool.io"
eth.ws = ""

arbitrum.http = "https://rinkeby.arbitrum.io/rpc"
arbitrum.ws = ""

polygon.http = "https://rpc-mumbai.maticvigil.com"
polygon.ws = ""

solana.http = "https://api.testnet.solana.com"
solana.ws = ""

cosmos.http = "https://tendermint-test"
cosmos.ws = ""

evmos.http = "https://tendermint-test"
evmos.ws = ""

kava.http = "https://tendermint-test"
kava.ws = ""

juno.http = "https://tendermint-test"
juno.ws = ""

umee.http = "https://tendermint-test"
umee.ws = ""

gravity.http = "https://tendermint-test"
gravity.ws = ""

okc.http = "https://tendermint-test"
okc.ws = ""

irisnet.http = "https://tendermint-test"
irisnet.ws = ""

[[redis]]
database = 14
username = ""
password = ""
addr = "127.0.0.1:6379"

[[redis]]
database = 15
username = ""
password = ""
addr = "127.0.0.1:6379"

[log]
# debug, info, warn, error
level = "debug"
is_dev = true
log_file = "./starnet_chain_api.log"
